### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dohliam** [elias-schuett/JS1K-Entries#1]
Hi Elias, thanks for sharing your js1k entries, they're really cool! :+1: However I notice you didn't include a license. Would it be possible to release these under a free license so that they can be included in the [openjs1k](https://github.com/dohliam/openjs1k) project? Even if you don't plan on using a free license, having a license of some kind would help people know whether or not they can reuse your work. :smile:

**Comment by elias-schuett** [comment]
Hey, great project! Added the license.
Someone should tell @qfox.

**Comment by qfox** [comment]
As far as js1k.com goes, people agree allowing me to use their submission on the site and, optionally, for merchendise (though that's not been relevant yet). I'm not concerned by anything else and you'll have to hunt those licenses yourself :)

**Comment by dohliam** [comment]
@qfox Fair enough. It would be awesome if the submission form had a drop-down to let contestants select a license though (like on github or flickr)!
![GitHub license dropdown](https://www.conorgriffin.com/static/img/3-github-choose-a-license.png)

**Comment by qfox** [comment]
Not likely to happen any time soon. But thanks for the suggestion.

As far as I'm concerned the source code is right up there. If you want to learn from it you can (try to) read it. If people want to publish the original source code or a license they are free to do so in their description or original source fields, even retroactively through the update form (http://js1k.com/update).

If they don't want to then that's fine and I'm not going to push them to make that choice. I'm not too concerned about entries not having a license (beyond allowing me to publish them on js1k.com of course). If you're really dead set on getting these licenses most runners supply a twitter handle to contact them on. And from this year on alternative social information can be added as well. So you know... there's options there. If you really really want to.

**Comment by dohliam** [comment]
@qfox Thanks for your response! I'd just like to say that I'm a huge fan of the competition and all the hard work you and everyone else puts into organizing and running it, so I definitely didn't want to give you more work to do. (By my calculation there have been slightly more than 1100 entries to all competitions so far... and that's just those that were accepted. It's incredible that you manage to go through all of them!).

I noticed that you expanded the social media fields in the submission form this year, which is great. It's particularly helpful now that most entries have links to GitHub, so people can follow up there with the author if they want to. Just to clarify, I agree with you that there's no need to push people to choose a license -- I just thought it would be nice to give the option of choosing one from a list in the submission form (or even just an extra optional textbox called "License" underneath the ones for Google+ and Facebook). Of course, that can always be added to the description, as you said, so I understand if there's no rush to implement this. :smile: 

Speaking of descriptions, were you aware that the details pages for the 2011 competition have been broken for some time? (For example, [here's the link](http://js1k.com/2011-trail/details/984) to the details page for the top ranking demo for that year.) I know the links changed a while ago, so perhaps that had something to do with it.

**Comment by dohliam** [comment]
@elias-schuett Thanks very much! I've added your entries to the list in the last commit. The newest demo you added ([Romanesco](http://js1k.com/2015-hypetrain/demo/2161)), is amazing. It also made me realize that I need to add a new category for webgl stuff -- should happen in the next commit or so.
